#ifndef _BTRFS_STUBS_H
#define _BTRFS_STUBS_H

#include <fcntl.h>
#include <linux/fs.h>
#include <sys/types.h>

struct iovec;

ssize_t pwritev2(int fd, const struct iovec *iov, int iovcnt, off_t offset,
		 int flags);

#ifndef O_ALLOW_ENCODED
#if defined(__alpha__)
#define O_ALLOW_ENCODED      0200000000
#elif defined(__hppa__)
#define O_ALLOW_ENCODED      100000000
#elif defined(__sparc__)
#define O_ALLOW_ENCODED      0x8000000
#else
#define O_ALLOW_ENCODED      040000000
#endif
#endif

#ifndef RWF_ENCODED

enum {
        ENCODED_IOV_COMPRESSION_NONE,
#define ENCODED_IOV_COMPRESSION_NONE ENCODED_IOV_COMPRESSION_NONE
        ENCODED_IOV_COMPRESSION_BTRFS_ZLIB,
#define ENCODED_IOV_COMPRESSION_BTRFS_ZLIB ENCODED_IOV_COMPRESSION_BTRFS_ZLIB
        ENCODED_IOV_COMPRESSION_BTRFS_ZSTD,
#define ENCODED_IOV_COMPRESSION_BTRFS_ZSTD ENCODED_IOV_COMPRESSION_BTRFS_ZSTD
        ENCODED_IOV_COMPRESSION_BTRFS_LZO_4K,
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_4K ENCODED_IOV_COMPRESSION_BTRFS_LZO_4K
        ENCODED_IOV_COMPRESSION_BTRFS_LZO_8K,
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_8K ENCODED_IOV_COMPRESSION_BTRFS_LZO_8K
        ENCODED_IOV_COMPRESSION_BTRFS_LZO_16K,
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_16K ENCODED_IOV_COMPRESSION_BTRFS_LZO_16K
        ENCODED_IOV_COMPRESSION_BTRFS_LZO_32K,
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_32K ENCODED_IOV_COMPRESSION_BTRFS_LZO_32K
        ENCODED_IOV_COMPRESSION_BTRFS_LZO_64K,
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_64K ENCODED_IOV_COMPRESSION_BTRFS_LZO_64K
        ENCODED_IOV_COMPRESSION_TYPES = ENCODED_IOV_COMPRESSION_BTRFS_LZO_64K,
};

enum {
	ENCODED_IOV_ENCRYPTION_NONE,
#define ENCODED_IOV_ENCRYPTION_NONE ENCODED_IOV_ENCRYPTION_NONE
	ENCODED_IOV_ENCRYPTION_TYPES = ENCODED_IOV_ENCRYPTION_NONE,
};

struct encoded_iov {
	__aligned_u64 len;
	__aligned_u64 unencoded_len;
	__aligned_u64 unencoded_offset;
	__u32 compression;
	__u32 encryption;
};

#define ENCODED_IOV_SIZE_VER0 32

/* encoded (e.g., compressed and/or encrypted) IO */
#define RWF_ENCODED    ((__kernel_rwf_t)0x00000020)
#endif /* RWF_ENCODED */

#endif /* _BTRFS_STUBS_H */
